"""Target store + Smokeping Targets file renderer.

The source of truth for targets is ``targets.json`` (a list of target dicts).
Whenever it changes, :func:`render_smokeping_targets` regenerates the Smokeping
``Targets`` file (``SMOKEPING_TARGETS_FILE``, on the shared config volume). The
static config ``@include``s that file, so a reload picks up the new targets.

The Smokeping section hierarchy mirrors the RRD filesystem layout:
    + <group_slug>            ->  /data/<group_slug>/
    ++ <target_section_id>    ->  /data/<group_slug>/<target_section_id>.rrd
so ``rrd_reader`` can locate a target's RRD deterministically from the same
slug functions in ``validators``.
"""
from __future__ import annotations

import json
import logging
import os
import threading
from typing import Optional

import validators

log = logging.getLogger("smokeping_easy.config_writer")

DATA_DIR = os.environ.get("APP_DATA_DIR", "/app/data")
TARGETS_STORE = os.path.join(DATA_DIR, "targets.json")
GROUPS_STORE = os.path.join(DATA_DIR, "groups.json")
SMOKEPING_TARGETS_FILE = os.environ.get("SMOKEPING_TARGETS_FILE", "/config/Targets")

_lock = threading.RLock()

_HEADER = """*** Targets ***

probe = FPing

menu = Top
title = smokeping-easy
remark = Latency monitoring managed by smokeping-easy. \\
         Do not edit this file by hand; it is regenerated automatically.
"""


# --- Target store ----------------------------------------------------------


def load_targets() -> list[dict]:
    with _lock:
        if not os.path.exists(TARGETS_STORE):
            return []
        try:
            with open(TARGETS_STORE, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            return data if isinstance(data, list) else []
        except (json.JSONDecodeError, OSError) as exc:
            log.error("Could not read targets.json (%s)", exc)
            return []


def save_targets(targets: list[dict]) -> None:
    with _lock:
        os.makedirs(DATA_DIR, exist_ok=True)
        tmp = TARGETS_STORE + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(targets, fh, indent=2, ensure_ascii=False)
        os.replace(tmp, TARGETS_STORE)


def get_target(target_id: str) -> Optional[dict]:
    for t in load_targets():
        if t.get("id") == target_id:
            return t
    return None


# --- Group store -----------------------------------------------------------
# A group is {id, slug, name}. `slug` is filesystem/Smokeping-safe and
# IMMUTABLE (it anchors the RRD path), so renaming a group keeps its history.


def load_groups() -> list[dict]:
    with _lock:
        if not os.path.exists(GROUPS_STORE):
            return []
        try:
            with open(GROUPS_STORE, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            return data if isinstance(data, list) else []
        except (json.JSONDecodeError, OSError):
            return []


def save_groups(groups: list[dict]) -> None:
    with _lock:
        os.makedirs(DATA_DIR, exist_ok=True)
        tmp = GROUPS_STORE + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(groups, fh, indent=2, ensure_ascii=False)
        os.replace(tmp, GROUPS_STORE)


def get_group(group_id: str) -> Optional[dict]:
    for g in load_groups():
        if g.get("id") == group_id:
            return g
    return None


def _unique_slug(name: str, groups: list[dict]) -> str:
    base = validators.slugify(name, "group")
    existing = {g["slug"] for g in groups}
    slug, i = base, 2
    while slug in existing:
        slug, i = f"{base}_{i}", i + 1
    return slug


def create_group(name: str, is_default: bool = False) -> dict:
    with _lock:
        groups = load_groups()
        for g in groups:  # de-dupe by name (case-insensitive)
            if g["name"].strip().lower() == name.strip().lower():
                return g
        group = {"id": validators.new_uuid(), "slug": _unique_slug(name, groups), "name": name.strip()}
        if is_default:
            group["is_default"] = True
        groups.append(group)
        save_groups(groups)
        return group


def rename_group(group_id: str, name: str) -> Optional[dict]:
    with _lock:
        groups = load_groups()
        found = next((g for g in groups if g["id"] == group_id), None)
        if not found:
            return None
        found["name"] = name.strip()
        save_groups(groups)
        # Update the denormalised name on member targets (slug/path unchanged).
        targets = load_targets()
        for t in targets:
            if t.get("group_id") == group_id:
                t["group"] = found["name"]
        save_targets(targets)
        return found


def delete_group(group_id: str) -> str:
    """Delete a group. Returns a status code:
    'ok' | 'not_found' | 'default' (protected) | 'in_use' (has targets)."""
    with _lock:
        g = get_group(group_id)
        if g is None:
            return "not_found"
        if g.get("is_default"):
            return "default"
        if any(t.get("group_id") == group_id for t in load_targets()):
            return "in_use"
        groups = [x for x in load_groups() if x["id"] != group_id]
        save_groups(groups)
        return "ok"


def find_or_create_group_by_name(name: str) -> dict:
    name = (name or "Default").strip() or "Default"
    for g in load_groups():
        if g["name"].strip().lower() == name.lower():
            return g
    return create_group(name)


def ensure_default_group() -> dict:
    """Guarantee exactly one protected default group exists."""
    with _lock:
        groups = load_groups()
        existing = next((g for g in groups if g.get("is_default")), None)
        if existing:
            return existing
        if groups:
            # Promote the group named "Default" (or the first) to be the default.
            target = next((g for g in groups if g["name"].strip().lower() == "default"), groups[0])
            target["is_default"] = True
            save_groups(groups)
            return target
        return create_group("Default", is_default=True)


def migrate_target_groups() -> None:
    """Backfill group_id on targets created before groups were first-class.

    Groups are seeded from the targets' current group names, with slug =
    slugify(name) — identical to the old RRD path — so no data moves.
    """
    with _lock:
        targets = load_targets()
        changed = False
        for t in targets:
            if not t.get("group_id"):
                g = find_or_create_group_by_name(t.get("group") or "Default")
                t["group_id"] = g["id"]
                t["group"] = g["name"]
                changed = True
        if changed:
            save_targets(targets)


# --- RRD path mapping ------------------------------------------------------


def slug_for_target(target: dict) -> str:
    """Stable group slug for a target (via its group_id), with a fallback."""
    gid = target.get("group_id")
    if gid:
        g = get_group(gid)
        if g:
            return g["slug"]
    return validators.group_slug(target.get("group"))


def rrd_relative_segments(target: dict) -> tuple[str, str]:
    """Return (group_slug, '<section_id>.rrd') for a target."""
    gslug = slug_for_target(target)
    section = validators.target_section_id(target.get("id", ""))
    return gslug, f"{section}.rrd"


# --- Smokeping Targets rendering -------------------------------------------


def _escape(value: str) -> str:
    """Keep target labels/titles on a single Smokeping config line."""
    return (value or "").replace("\n", " ").replace("\r", " ").strip()


def render_targets_config(targets: list[dict]) -> str:
    lines = [_HEADER]

    # Group targets by their (stable) group slug, using the managed group name
    # as the menu label. Falls back to the denormalised name for old targets.
    groups_by_id = {g["id"]: g for g in load_groups()}
    groups: dict[str, dict] = {}
    for t in targets:
        g = groups_by_id.get(t.get("group_id"))
        if g:
            gslug, label = g["slug"], g["name"]
        else:
            gslug, label = validators.group_slug(t.get("group")), (t.get("group") or "Default")
        grp = groups.setdefault(gslug, {"label": label, "items": []})
        grp["items"].append(t)

    if not groups:
        # Smokeping needs at least one target section to be happy.
        lines.append("\n+ Default\nmenu = Default\ntitle = No targets yet\n")
        return "\n".join(lines) + "\n"

    for gslug, grp in groups.items():
        lines.append(f"\n+ {gslug}")
        lines.append(f"menu = {_escape(grp['label'])}")
        lines.append(f"title = {_escape(grp['label'])}")
        for t in grp["items"]:
            section = validators.target_section_id(t.get("id", ""))
            host = t["host"]
            probe = validators.probe_for_host(host)
            lines.append(f"\n++ {section}")
            lines.append(f"menu = {_escape(t.get('label') or host)}")
            lines.append(f"title = {_escape(t.get('label') or host)}")
            # Smokeping requires `probe` to appear BEFORE `host`. Base probe is
            # FPing (inherited); override only for IPv6 hosts.
            if probe != "FPing":
                lines.append(f"probe = {probe}")
            lines.append(f"host = {host}")

    return "\n".join(lines) + "\n"


def render_smokeping_targets(targets: Optional[list[dict]] = None) -> None:
    """Render and atomically write the Smokeping Targets file."""
    if targets is None:
        targets = load_targets()
    content = render_targets_config(targets)
    with _lock:
        target_dir = os.path.dirname(SMOKEPING_TARGETS_FILE)
        os.makedirs(target_dir, exist_ok=True)
        tmp = SMOKEPING_TARGETS_FILE + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.replace(tmp, SMOKEPING_TARGETS_FILE)
    log.info("Wrote %d target(s) to %s", len(targets), SMOKEPING_TARGETS_FILE)
